allowBuilds:
  '@playwright/browser-chromium': true
  '@vscode/vsce-sign': false
  keytar: false
minimumReleaseAgeExclude:
  - '@types/vscode@1.136.0'
  - '@vscode/vsce@4.0.0'
  - git-cliff-darwin-arm64@2.14.2
  - git-cliff-darwin-x64@2.14.2
  - git-cliff-linux-arm64@2.14.2
  - git-cliff-linux-x64@2.14.2
  - git-cliff-windows-arm64@2.14.2
  - git-cliff-windows-x64@2.14.2
  - git-cliff@2.14.2
